# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joshua England
tagline:          ''
description:      ''
url:              http://ethr.github.io
baseurl:             /

author:
  name:           'Joshua England'
  url:            http://ethr.githib.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ethr/ethr.github.io
